export const HOME_CASUAL = 'home_casual'  // 首页轮播图
export const HOME_NAV = 'home_nav'  // 获取首页nav
export const HOME_SHOPLIST = 'home_shoplist' // 获取首页商品列表数据
export const RECOMMEND_SHOPLIST = 'recommend_shoplist' // 推荐商品数据列表
export const SEARCH_GOODS = 'search_goods' // 搜索商品列表
export const USER_INFO = 'user_info' // 用户信息
export const RESET_USER_INFO = 'reset_userInfo' // 清空用户信息
export const CAR_GOODS_LIST = 'car_goods_list' // 购物车数据列表
export const ADD_GOODS_LIST = 'add_car_goods_list' // 增加购物车中数据
export const DOWN_GOODS_LIST = 'down_car_goods_list' // 减少购物车中数据
export const SELECT_ALL_GOODS = 'select_all_goods' // 是否选中所有的商品
export const SINGLE_SELECTED = 'single_selected' // 单个商品的选中
export const DEL_GOODS = 'del_goods' // 删除单个商品
export const ADD_CART = 'add_cart' // 加入购物车
export const SB_INFO = 'sb_info' // 用户信息
export const DAY_INFO = 'day_info' //每日健康数据
export const CHOOSE_MESS = 'choose_mess'  //每周健康数据
